# Site settings
title: Johannes Zierenberg
email: johannes.zierenberg@ds.mpg.de
description: > # this means to ignore newlines until "baseurl:"
  Scientific life of Johannes Zierenberg
baseurl: "/zierenberg.github.io" # the subpath of your site, e.g. /blog/
url: "http://zierenberg.github.io" # the base hostname & protocol for your site
twitter_username: jozierenberg
github_username:  zierenberg

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
  hard_wrap: false
